config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'cakes/new'
  resources :cakes
  root 'welcome#index'
  resources :cakes do
  resources :comments
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cake.rb
class Cake < ApplicationRecord
   has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :cake
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
   http_basic_authenticate_with name: "cupcake", password: "cupcake", except: [:index, :show, :new]

def new
	@cake = Cake.new
end
def index
	@cakes = Cake.all
	
end



def create
  @cake = Cake.new(cake_params)
 
 if @cake.save
  redirect_to @cake
else
	render 'new'
end
end
def edit
  @cake = Cake.find(params[:id])
end
def update
  @cake = Cake.find(params[:id])
 
  if @cake.update(cake_params)
    redirect_to @cake
  else
    render 'edit'
  end
end
def destroy
  @cake = Cake.find(params[:id])
  @cake.destroy
 
  redirect_to cakes_path
end

 def show
    @cake = Cake.find(params[:id])
  end
end
 
private
  def cake_params
    params.require(:cake).permit(:title, :text)
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @cake = Cake.find(params[:cake_id])
    @comment = @cake.comments.create(comment_params)
    redirect_to cake_path(@cake)
end
 
  def destroy
    @cake = Cake.find(params[:cake_id])
    @comment = @cake.comments.find(params[:id])
    @comment.destroy
    redirect_to cake_path(@cake)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/model_controller.rb
class ModelController < ApplicationController
  def cake
  end

  def title:string
  end

  def text:text
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cakes_helper.rb
module CakesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/model_helper.rb
module ModelHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cakes/_form.html.erb
<%= form_with model: @cake, local: true do |form| %>
 
  <% if @cake.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@cake.errors.count, "error") %> prohibited
        this cake from being saved:
      </h2>
      <ul>
        <% @cake.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <center>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p></center>
 
<% end %>

app/views/cakes/edit.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br><center><h1>Edit Cake Details</h1>
 
<%= render 'form' %>
 <%= button_to "Back", cakes_path, :method => "get" %></center>

app/views/cakes/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<center><h1>Listing Type Of Cake</h1>
 
<table  border="4pt" style="background:pink">
  <tr>
    <th>Type</th>
    <th>Flavour</th>
    <th colspan="3">CRUD</th>
  </tr>
 
  <% @cakes.each do |cake| %>
    <tr>
      <td><%= cake.title %></td>
      <td><%= cake.text %></td>
      <td><%= button_to "Show", cake_path(cake), :method => "get" %></td>
      <td><%= button_to "Edit", edit_cake_path(cake), :method => "get" %></td>
      <td><%= button_to "Delete", cake_path(cake),
               method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= button_to "New Cake", new_cake_path, :method => "get" %>
<%= button_to "Home Page", welcome_index_path, :method => "get" %></center>

app/views/cakes/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<br><center><h1>Add The New Cake</h1>
 
<%= render 'form' %>
 

<%= button_to "Back", cakes_path, :method => "get" %></center>

app/views/cakes/show.html.erb
<table  border="3pt" style="background:purple">
<tr>	
<p>
  <td><strong>Title:</strong></td>
  <td><%= @cake.title %></td>
</p>
 </tr>
 <tr>
<p>
  <td><strong>Text:</strong></td>
  <td><%= @cake.text %></td>
</p>
</tr>
</table>
<br>
<br>
<h3>Comments</h3>
<%= render @cake.comments %>

<br>
<br>
<h3>Add a comment:</h3>
<%= form_with(model: [ @cake, @cake.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
...
<%= button_to "Back", cakes_path, :method => "get" %>
<%= button_to "Edit", edit_cake_path, :method => "get" %>
	

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= button_to 'Delete Comment', [comment.cake, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cupcake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/model/cake.html.erb
<h1>Model#cake</h1>
<p>Find me in app/views/model/cake.html.erb</p>

app/views/model/text:text.html.erb
<h1>Model#text:text</h1>
<p>Find me in app/views/model/text:text.html.erb</p>

app/views/model/title:string.html.erb
<h1>Model#title:string</h1>
<p>Find me in app/views/model/title:string.html.erb</p>

app/views/welcome/index.html.erb
<body ><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<CENTER><p><font size="100pt" color="red">CupCake</font></p></CENTER>


<center>
<%= button_to "New Cake", new_cake_path, :method => "get" %>
<%= button_to "Go To Index", cakes_path, :method => "get" %>
</center>

</body>